# Generated by Django 5.1.7 on 2025-04-22 20:53

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
    ('accounts', '0001_initial'),
]


    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=True  # ✅ Allows us to add it without setting a default
            ),
        ),
    ]

