# Generated by Django 5.1.7 on 2025-04-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_password_userprofile_phone_number_and_more'),
        ('healthcheck', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcheck.team'),
        ),
    ]
