# Generated by Django 5.2 on 2025-04-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(db_column='TeamID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TeamName', max_length=50, unique=True)),
                ('size', models.CharField(db_column='TeamSize', max_length=50)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Stable', 'Stable'), ('Improving', 'Improving'), ('Getting worse', 'Getting worse')], max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('health_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcheck.healthcard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcheck.session')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ViewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(max_length=50)),
                ('view_date', models.DateField()),
                ('progress', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcheck.session')),
                ('vote_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcheck.votelog')),
            ],
        ),
    ]
