# Generated by Django 5.1.7 on 2025-04-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_password_userprofile_phone_number_and_more'),
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelog',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
