# Generated by Django 5.1.7 on 2025-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_votelog_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(db_column='TeamID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TeamName', max_length=50, unique=True)),
                ('size', models.CharField(db_column='TeamSize', max_length=50)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
    ]
